In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
a = np.array([1,2,33,444,789])
seri = pd.Series(a)
seri

0      1
1      2
2     33
3    444
4    789
dtype: int32

In [4]:
seri[0]

1

In [5]:
seri[0:3]

0     1
1     2
2    33
dtype: int32

In [6]:
seri2 = pd.Series([121,200,150,99],index = ["reg","loj","cart","rf"])
seri2

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [7]:
seri2.index

Index(['reg', 'loj', 'cart', 'rf'], dtype='object')

serinin indeks değerlerinin bilgilerine ulaştık

In [8]:
seri.keys

<bound method Series.keys of 0      1
1      2
2     33
3    444
4    789
dtype: int32>

In [9]:
list(seri.items())

[(0, 1), (1, 2), (2, 33), (3, 444), (4, 789)]

Her bir key değerine karşılık gelen value değeleriyle birlikte tuple halinde bir dizi içine atarak döndürdük. Her bir key değeri aynı zamanda o value değerinin indeks bilgisidir

In [10]:
seri.values

array([  1,   2,  33, 444, 789])

serinin sadece asıl değerlerini numpy arrayi biçiminde döndürür

### Eleman Sorgulama

In [11]:
seri

0      1
1      2
2     33
3    444
4    789
dtype: int32

In [12]:
seri2

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [13]:
"reg" in seri2 # seri2 serisinde "reg" keyi var mı?

True

In [14]:
"a" in seri # seri serisinde "a" keyi var mı?

False

Sorgu serinin key değerleri özelinde yapılır

#### Fancy eleman

Fancy index yaklaşımıyla da seri içindeki elemanlara ulaşabiliriz

In [15]:
seri2[["rf","reg"]]

rf      99
reg    121
dtype: int64

seri2 serisi içinde "rf" ve "reg" value değerlerine sahip elemanlara ulaştık

### Serilerde Slicing

In [16]:
seri2

reg     121
loj     200
cart    150
rf       99
dtype: int64

In [17]:
seri2["reg":"cart"]

reg     121
loj     200
cart    150
dtype: int64

seri2 serisindeki reg keyli değerden cart keyli değere ulaştık. key değerleri string iken stop noktası da slicing işlemine dahil edilir

In [18]:
seri

0      1
1      2
2     33
3    444
4    789
dtype: int32

In [19]:
seri[0:3]

0     1
1     2
2    33
dtype: int32

doğal indeksleme sağlanmışsa slicing işlemi standart şekilde gerçekleşir. Stop noktası dahil edilmez

In [23]:
seri3 = pd.Series([94,72,56,66,12], index = [1,3,5,7,9])
seri3
# doğal indekslemenin dışına çıkarak kendimiz indeks değerlerini atadık

1    94
3    72
5    56
7    66
9    12
dtype: int64

In [24]:
seri3[1:5]

3    72
5    56
7    66
9    12
dtype: int64

Sayısal yeniden indeksleme sağlandığında atanılan indeks numaralarıyla değil yine doğal indekslemeler göz önüne alınarak slicing işlemi gerçekleşir

In [25]:
seri3[7]

66

Fakat elemana ulaşmak istediğimizde atadığımız indeks değeri ile işlem yaparız. Yani bir nevi key değerleriyle işlem yaparız

### Eleman Değiştirme

In [20]:
seri2["reg"]

121

In [21]:
seri2["reg"] = 130
seri2["reg"]

130

seri2 serisindeki reg keyli elemanın value değerini 121 iken 130 yaptık